---
- name: "Configure debconf"
  ansible.builtin.debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ __postfix_debconf_selections }}"

- name: "Install postfix packages"
  ansible.builtin.package:
    name: ['postfix']
    state: present
  register: pkg_result
  retries: 12
  delay: 10
  until: pkg_result is success

- name: "Configure main.cf"
  ansible.builtin.template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0640'
    backup: true
  notify: Restart postfix

- name: "Configure master.cf"
  ansible.builtin.template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: '0640'
    backup: true
  notify: Restart postfix

- name: "Create postfix files"
  ansible.builtin.template:
    src: postfix_extra_files.j2
    dest: "/etc/postfix/{{ item }}"
    owner: root
    group: root
    mode: '0600'
  with_items:
    "{{ postfix_extra_files }}"
  when:
    - postfix_extra_files is defined
    - postfix_extra_files | length > 0
  notify:
    - Reload postfix

- name: "Postmap files"
  ansible.builtin.command: postmap /etc/postfix/{{ item }}
  changed_when: false
  with_items:
    "{{ postfix_extra_files }}"
  when:
    - postfix_extra_files is defined
    - postfix_extra_files | length > 0

- name: "Include sasl tasks"
  ansible.builtin.include_tasks: sasl.yml
  when:
    - postfix_sasl_install is defined
    - postfix_sasl_install | bool

- name: "Include opendkim tasks"
  ansible.builtin.include_tasks: opendkim.yml
  when:
    - postfix_dkim_install is defined
    - postfix_dkim_install | bool

- name: "Rebuild newaliases"
  ansible.builtin.command: newaliases
  changed_when: false
