---
- name: "Install sasl packages"
  ansible.builtin.package:
    name: ['sasl2-bin', 'libsasl2-modules']
    state: present
  register: pkg_result
  retries: 12
  delay: 10
  until: pkg_result is success

- name: "Add postfix to sasl group"
  ansible.builtin.user:
    name: postfix
    groups: sasl
    append: true

- name: "Configure /etc/default/saslauthd"
  ansible.builtin.template:
    src: default_saslauthd.j2 
    dest: /etc/default/saslauthd
    owner: root
    group: root
    mode: '0640'
    backup: true
  notify: Restart saslauthd

- name: "Configure /etc/saslauthd.conf"
  ansible.builtin.template:
    src: saslauthd.conf.j2
    dest: /etc/saslauthd.conf
    mode: '0440'
    owner: root
    group: root
  notify: Restart saslauthd

- name: Start saslauthd
  ansible.builtin.systemd:
    name: saslauthd
    state: started
    enabled: true
