---
- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: Reload postfix
  ansible.builtin.service:
    name: postfix
    state: reloaded

- name: Restart saslauthd
  ansible.builtin.service:
    name: saslauthd
    state: restarted
